upstream:
  backstage:
    extraEnvVars:
      - name: "APP_CONFIG_app_baseUrl"
        value: "https://{{ .Values.global.host }}"
      - name: "APP_CONFIG_backend_baseUrl"
        value: "https://{{ .Values.global.host }}"
      - name: "APP_CONFIG_backend_cors_origin"
        value: "https://{{ .Values.global.host }}"
  ingress:
    enabled: false
route:
  enabled: true
  host: "{{ .Values.global.host }}"

global:
  host: janusidp.test.com
